[project]
name = "todo-streamlit"
version = "0.1.0"
description = "Пример приложения на Streamlit"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "streamlit>=1.44.0",
]
